# Generated by Django 6.0.4 on 2026-05-08 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('image', models.ImageField(upload_to='user_uploads/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('generated_image', models.ImageField(upload_to='generated_images/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('dress_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_images', to='adminapp.categoryimage')),
                ('user_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_images', to='mainapp.useruploadedimage')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key', '-created_at'], name='mainapp_gen_session_1a1210_idx')],
            },
        ),
    ]
