# Generated by Django 6.0.4 on 2026-05-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryimage',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoryimage',
            name='dress_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoryimage',
            name='web_url',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
