# Generated by Django 6.0.4 on 2026-05-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_categoryimage_brand_name_categoryimage_dress_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='web_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
