# Generated by Django 6.0.4 on 2026-05-22 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_categoryimage_web_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Categories'},
        ),
    ]
